#!/bin/bash
# .claude/hooks/block-attribution.sh
# PreToolUse hook: blocks any git commit whose message references
# Anthropic or Claude. Exit 2 = block (exit 1 would NOT block).
INPUT=$(cat)
CMD=$(echo "$INPUT" | jq -r '.tool_input.command // empty')
if ! echo "$CMD" | grep -qE '\bgit\b.*\bcommit\b'; then
    exit 0
fi
if echo "$CMD" | grep -qiE 'anthropic|claude|co-authored-by|generated with|generated by'; then
    echo "BLOCKED: commit message must not reference Anthropic or Claude. Rewrite cleanly and commit again." >&2
    exit 2
fi
exit 0