// Copyright 2026 Sebastián Moreno Saavedra
// SPDX-License-Identifier: Apache-2.0

package router

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/Sebastian197/korvun/internal/envelope"
)

// This file is the B9 direct-brain conversation-id contract (spec
// 2026-08-29-b9-brain-selector-new-chat.md): a conversation id of the form
// "b:<pct-encoded brain>:<rest>" — generated by the console frontend when
// the operator picks a brain on New chat — carries the brain choice inside
// the conversation's persisted identity, so it survives restarts with zero
// storage change. The contract is honored ONLY on the channel enabled via
// WithDirectBrainChannel: on every other channel the prefix is inert data
// (the privacy invariant — a network-fabricated conversation_id must never
// bypass its route).

// directBrainFromConversationID parses the "b:<enc>:<rest>" contract.
// The name is percent-decoded (the frontend encodes with
// encodeURIComponent, which escapes ":" — so the two delimiters are
// unambiguous for any legal brain name). A malformed or empty segment is
// NOT the contract: the id is ordinary data, ok=false.
func directBrainFromConversationID(id string) (string, bool) {
	rest, found := strings.CutPrefix(id, "b:")
	if !found {
		return "", false
	}
	enc, tail, found := strings.Cut(rest, ":")
	if !found || enc == "" || tail == "" {
		return "", false
	}
	name, err := url.PathUnescape(enc)
	if err != nil || name == "" {
		return "", false
	}
	return name, true
}

// brainFallbackNotice is the sealed Spanish notice a conversation receives
// when its id names a brain that no longer exists (FR-B9-2, ola2-designs §1).
func brainFallbackNotice(name string) string {
	return fmt.Sprintf("El cerebro %q ya no existe — esta conversación continúa con el cerebro por defecto.", name)
}

// maybeSendBrainFallback sends the honest fallback notice for one
// conversation, deduplicated in a bounded window so a message burst warns
// once (FR-B9-2; the resource-bound invariant — the window, not a map,
// holds the per-conversation state). Addressed like triggerAck: the
// inbound's echoed Meta plus the ack mark the self-persisting console
// channel records as a SYSTEM turn.
func (r *Router) maybeSendBrainFallback(env *envelope.Envelope, ghost string) {
	r.brainFallbackOnce.Do(func() {
		r.brainFallbackWarned = newDedupWindow(DedupCapacity, DedupTTL, r.clock)
	})
	key := env.Channel + "::" + env.Meta[MetaConversationID]
	if r.brainFallbackWarned.seen(key) {
		return
	}
	out := envelope.New(env.Channel, envelope.Outbound, korvun).AddText(brainFallbackNotice(ghost))
	for k, v := range env.Meta {
		out.Meta[k] = v
	}
	out.Meta[envelope.MetaAck] = envelope.AckBrainFallback
	r.sendReply(out)
}
